// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9n9bX4p5SNhSv8obE8PF4QtCzp87nHhc',
    appId: '1:396305200824:web:a0e2192b16bcbb6cbce64d',
    messagingSenderId: '396305200824',
    projectId: 'weather-mobile-app-adb21',
    authDomain: 'weather-mobile-app-adb21.firebaseapp.com',
    databaseURL:
        'https://weather-mobile-app-adb21-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-mobile-app-adb21.appspot.com',
    measurementId: 'G-KB132KNCF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnE9V7RJ6WHw0NLuKX0YmBwqq31npbbRM',
    appId: '1:396305200824:android:24611ee597e6242dbce64d',
    messagingSenderId: '396305200824',
    projectId: 'weather-mobile-app-adb21',
    databaseURL:
        'https://weather-mobile-app-adb21-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weather-mobile-app-adb21.appspot.com',
  );
}
